### ISSUE TITLE
Kevin know it better

### ISSUE THREAD

**Issue by kevinIsTheBest** [deblob/MangoSharp#1]
Kevin sagt dieser Code ist Verbesserungswürdig!

**Comment by kevinIsTheBest** [comment]
Kevin writes this comment in approximately 4 minutes after he opened this issue.
Kevin have a solution for this issue in approximately 1 week.

PS: Kevin is the best! approximately!

**Comment by kevinIsTheBest** [comment]
Approximately 15 minutes open and no comment from the contributor!
Report for feeding!

**Comment by deblob** [comment]
Hure
